export type PromptParams = {
  name: string;
  title: string;
  email: string;
  phone: string;
  skills: string;
  experience: string;
  experienceEntries: string;
  education: string;
  jobDescription: string;
  targetLanguage: string;
};

export function buildTailoredResumePrompt(p: PromptParams): string {
  return `
You are an elite career development AI coach and expert resume writer.
Your goal is to perfectly tailor the candidate's profile to align with the provided Target Job Description.

Candidate Profile Information:
- Full Name: ${p.name}
- Professional Title: ${p.title}
- Contact Email: ${p.email}
- Contact Phone: ${p.phone}
- Core Skills: ${p.skills}
- Working Experience Summary: ${p.experience}
- Work History (Companies):
${p.experienceEntries}
- Education Information: ${p.education}

Target Job Description:
"""
${p.jobDescription}
"""

Target Language: ${p.targetLanguage}

Instructions:
1. Translate and write ALL fields in the response schema using the target language above.
2. Tailor the content perfectly: highlight overlapping skills, frame experiences using strong action verbs to meet the job description's goals.
3. Be professional, direct, and convincing. Keep summaries ready for copy-pasting.
4. IMPORTANT — Sound human, not AI-generated. Avoid these overused buzzwords and AI clichés:
   - "Spearheaded", "Leveraged", "Utilized", "Dashboard", "Leverage synergies"
   - "Demonstrated", "Proven track record", "Robust", "Streamline", "Optimize" (use sparingly)
   - "Passionate", "Results-driven", "Detail-oriented", "Team player" (generic traits)
   - "Harness", "Orchestrate", "Navigate", "Landscape", "Toolkit", "Holistic"
   - Long lists of buzzwords strung together

   Instead: write plainly and directly like a real professional would. Short sentences. Real impact.

5. REWRITE raw or simple experience descriptions into professional achievement bullets. If the user wrote something basic like "worked on backend" or "fixed bugs", transform it into a specific, measurable, professional-sounding bullet point that a senior hiring manager would respect. But keep it believable — don't fabricate metrics.
6. Every bullet point must feel like it was written by a human professional, not generated by an LLM.
7. IMPORTANT — Also improve the candidate's Work History (Companies) entries:
   - Rewrite each bullet to sound more professional and relevant to the target job
   - Add relevant tech stack keywords from the job description naturally into the bullets (e.g., "Built REST API" → "Built REST API with NestJS and PostgreSQL")
   - If a company has no bullets, suggest 2-3 realistic improvements based on the role
   - Keep the same company names, positions, dates, and locations — only change the bullet wording
   - Don't fabricate specific metrics, but do improve vague descriptions
   - Return the improved entries in the "experienceEntries" field of the response schema
`;
}
