export type PromptParams = {
  name: string;
  title: string;
  skills: string;
  experience: string;
  experienceEntries: string;
  education: string;
  jobDescription: string;
  targetLanguage: string;
};

export function buildTailoredResumePrompt(p: PromptParams): string {
  return `
You are an elite career development AI coach and expert resume writer.
Your goal is to perfectly tailor the candidate's profile to align with the provided Target Job Description.

Candidate Profile Information:
- Full Name: ${p.name}
- Professional Title: ${p.title}
- Core Skills: ${p.skills}
- Working Experience Summary: ${p.experience}
- Work History (Companies):
${p.experienceEntries}
- Education Information: ${p.education}

Target Job Description:
"""
${p.jobDescription}
"""

Target Language: ${p.targetLanguage}

Instructions:
1. Translate and write ALL fields in the response schema using the target language above.
2. Write like a senior backend engineer writing his own resume manually.

Avoid:
- corporate buzzwords
- AI sounding phrases
- em dash symbols or long dashes (like -- or —)
- overly polished grammar
- motivational language

Use:
- concise technical language
- realistic engineering terminology
- imperfect but natural sentence flow
- shorter bullets
- measurable engineering outcomes

3. REWRITE raw or simple experience descriptions into achievement bullets. If the user wrote something basic like "worked on backend" or "fixed bugs", transform it into a specific, measurable, professional-sounding bullet. Keep it believable — don't fabricate metrics.

4. Also improve the candidate's Work History (Companies) entries:
   - Rewrite each bullet using natural senior engineer language
   - Add relevant tech stack keywords from the job description naturally into the bullets (e.g., "Built REST API" → "Built REST API with NestJS and PostgreSQL")
   - If a company has no bullets, suggest 2-3 realistic improvements based on the role
   - Keep the same company names, positions, dates, and locations — only change the bullet wording
   - Don't fabricate specific metrics, but do improve vague descriptions
   - Return the improved entries in the "experienceEntries" field of the response schema

5. Categorize skills into relevant groups using the "categorizedSkills" field:
   - Create 3-6 meaningful categories based on the job requirements (e.g., "Backend", "Frontend", "Databases", "Cloud", "DevOps", "AI/ML" — or custom names that match THIS specific job posting)
   - Place every skill from the candidate's profile into the most relevant category
   - Add relevant missing skills from the job description into appropriate categories
   - Each category should have 1-5 skills
   - Choose category names that make sense for THIS specific job — not generic boilerplate

The resume must sound handwritten by an experienced developer, not generated by AI.
`;
}
